name: Reusable - CDK Synth

on:
  workflow_call:

jobs:
  cdk-synth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: "24"
          cache: npm
          cache-dependency-path: |
            package-lock.json
            infra/package-lock.json

      - run: npm ci

      - run: npm ci
        working-directory: infra

      - name: CDK Synth
        run: npx cdk synth
        working-directory: infra
        env:
          SLACK_BOT_TOKEN: dummy
          SLACK_SIGNING_SECRET: dummy
          TIMES_ALL_CHANNEL_ID: C0000000000
          WORKSPACE_URL: https://dummy.slack.com
