name: on Pull Request
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  check:
    uses: ./.github/workflows/_reusable_check.yml

  lambda-rie-test:
    uses: ./.github/workflows/_reusable_lambda_rie_test.yml

  cdk-synth:
    uses: ./.github/workflows/_reusable_cdk_synth.yml
